### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by shinenelson**
Change Log : 
- Changed Siraj's name in credits
- Fixed Top button overlap with T&C

### CODE REVIEW

**Comment by riverspirit** [comment]
I've merged this PR, but in the future, please either
1. Make separate pull requests for each change/commit so that one of them can be rejected if needed.
2. OR If you are making a collective PR for different changes like this one, please discuss all the changes in advance.

**Comment by shinenelson** [comment]
The problem with PR is that I cannot send more than one PR at a time. I
cannot send a second PR when my first one is still pending. I tried last
night. I had 3 levels of PRs of which this was the first. The other 2 are
coming behind this one.

_Cheers,_
*shine *
   https://about.me/shinenelson[image:
about.me]https://about.me/shinenelson [image:
Facebook] https://facebook.com/divine.shine [image: Google
+]https://plus.google.com/+shinenelson [image:
LinkedIn] https://linkedin.com/in/shinenelson [image:
Klout]http://klout.com/%7E65583674340078479

Web Project Driver | mozillakerala
Student Ambassador | mozilla Firefox
Enthusiast |
_Free & Open Source Software (FOSS)_Contributor | _spoken-tutorial.org
http://spoken-tutorial.org_
Core Team Member | DevLooop | Startup Village
Member | mozillakerala
Developer\* |\* Firefox OS
Developer\* |\* android
radioactive.life@gmail.com

**Comment by riverspirit** [comment]
Yeah. You can have only 1 open PR per branch. You can try creating a new feature branch and making PR's from them, or more easily, just wait for your first PR to be closed/merged.

Or you can just discuss all the changes you are going to be sending in your PR in advance and we can reach a mutual agreement on them and then you can open a combined PR.

If you want to know more about creating feature branches and making PR's from them, read [this](https://gun.io/blog/how-to-github-fork-branch-and-pull-request/).

**Comment by riverspirit** [comment]
And it would be nice to trim your long signature from the comments.

**Pull request merged**
